SELECT TOP (1000) [Order Id]
      ,[Order Date]
      ,[Ship Mode]
      ,[Segment]
      ,[Country]
      ,[City]
      ,[State]
      ,[Postal Code]
      ,[Region]
      ,[Category]
      ,[Sub Category]
      ,[Product Id]
      ,[cost price]
      ,[List Price]
      ,[Quantity]
      ,[Discount Percent]
  FROM [Olist_db].[dbo].[olist_orders]
